name: Gradle CI

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  packages: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      # Checking up
      - uses: actions/checkout@v4
      # Setting up Java 21
      - name: JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      # Publishing
      - name: publish
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publishPackagesPublicationToGprRepository --no-daemon
        env:
          # GitHub Packages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
